[build]
  command = "npm run build"
  publish = "dist/my-angular-prelimBadge"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
